# Generated by Django 4.2.7 on 2025-11-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('promissory_note', 'Senet'), ('contract', 'Sözleşme'), ('report', 'Rapor'), ('receipt', 'Dekont')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('related_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Yaklaşan'), ('delayed', 'Geciken'), ('completed', 'Tamamlandı'), ('reminder', 'Hatırlatma')], default='upcoming', max_length=20)),
            ],
        ),
    ]
