# Generated by Django 4.2.7 on 2025-11-12 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('template_type', models.CharField(choices=[('contract', 'Sözleşme'), ('promissory_note', 'Senet'), ('report', 'Rapor')], max_length=50, verbose_name='Şablon Türü')),
                ('content_html', models.TextField(verbose_name='HTML İçerik')),
                ('placeholders', models.JSONField(blank=True, default=list, null=True, verbose_name="Placeholder'lar")),
                ('usage_count', models.IntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('versioning', models.JSONField(blank=True, default=dict, null=True, verbose_name='Versiyon Geçmişi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Şablon',
                'verbose_name_plural': 'Şablonlar',
                'db_table': 'templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_type'], name='templates_templat_96f569_idx'), models.Index(fields=['title'], name='templates_title_2d0106_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tutar')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Para Birimi')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('level', models.CharField(choices=[('company', 'Şirket'), ('brand', 'Marka'), ('branch', 'Şube'), ('person', 'Kişi')], default='branch', max_length=10, verbose_name='Seviye')),
                ('level_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seviye ID')),
                ('tags', models.JSONField(blank=True, default=list, null=True, verbose_name='Etiketler')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True, verbose_name='Meta Veri')),
                ('attachments', models.ManyToManyField(blank=True, to='common.uploadedfile', verbose_name='Ekler')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Dekont',
                'verbose_name_plural': 'Dekontlar',
                'db_table': 'receipts',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='receipts_date_64e609_idx'), models.Index(fields=['level'], name='receipts_level_c40212_idx'), models.Index(fields=['level_object_id'], name='receipts_level_o_5601bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('start', models.DateTimeField(verbose_name='Başlangıç')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('category', models.CharField(choices=[('upcoming_payment', 'Yaklaşan Ödeme'), ('overdue_payment', 'Gecikmiş Ödeme'), ('new_contract', 'Yeni Sözleşme'), ('promissory_note', 'Senet'), ('report_reminder', 'Rapor Hatırlatma')], max_length=50, verbose_name='Kategori')),
                ('related_document_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlişkili Doküman Tipi')),
                ('related_document_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlişkili Doküman ID')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('related_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.branch', verbose_name='İlişkili Şube')),
                ('related_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.brand', verbose_name='İlişkili Marka')),
                ('related_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.company', verbose_name='İlişkili Şirket')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.person', verbose_name='İlişkili Kişi')),
            ],
            options={
                'verbose_name': 'Takvim Etkinliği',
                'verbose_name_plural': 'Takvim Etkinlikleri',
                'db_table': 'calendar_events',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['start'], name='calendar_ev_start_90c81e_idx'), models.Index(fields=['category'], name='calendar_ev_categor_4b382b_idx')],
            },
        ),
    ]
